import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Dashboard/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


const font = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400","500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} antialiased bg-[#1e2233]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
